/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.study.updateol.avro.newprotocol;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface NewAvroService {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"NewAvroService\",\"namespace\":\"com.study.updateol.avro.newprotocol\",\"types\":[{\"type\":\"record\",\"name\":\"NewPerson\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"id\",\"type\":\"int\"},{\"name\":\"email\",\"type\":\"string\"}]},{\"type\":\"record\",\"name\":\"NewCompany\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"address\",\"type\":\"string\"}]},{\"type\":\"record\",\"name\":\"NewAddressBook\",\"fields\":[{\"name\":\"personList\",\"type\":{\"type\":\"array\",\"items\":\"NewPerson\"}},{\"name\":\"companyList\",\"type\":{\"type\":\"array\",\"items\":\"NewCompany\"}}]}],\"messages\":{\"send\":{\"request\":[{\"name\":\"addressBook\",\"type\":\"NewAddressBook\"}],\"response\":\"string\"}}}");
  /**
   */
  CharSequence send(NewAddressBook addressBook) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends NewAvroService {
    public static final org.apache.avro.Protocol PROTOCOL = NewAvroService.PROTOCOL;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void send(NewAddressBook addressBook, org.apache.avro.ipc.Callback<CharSequence> callback) throws java.io.IOException;
  }
}