/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.study.updateol.avro.newprotocol;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class NewAddressBook extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8413514123362477458L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"NewAddressBook\",\"namespace\":\"com.study.updateol.avro.newprotocol\",\"fields\":[{\"name\":\"personList\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"NewPerson\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"id\",\"type\":\"int\"},{\"name\":\"email\",\"type\":\"string\"}]}}},{\"name\":\"companyList\",\"type\":[{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"NewCompany\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"address\",\"type\":\"string\"}]}},\"null\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<NewAddressBook> ENCODER =
      new BinaryMessageEncoder<NewAddressBook>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<NewAddressBook> DECODER =
      new BinaryMessageDecoder<NewAddressBook>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<NewAddressBook> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<NewAddressBook> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<NewAddressBook>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this NewAddressBook to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a NewAddressBook from a ByteBuffer. */
  public static NewAddressBook fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.util.List<NewPerson> personList;
  @Deprecated public java.util.List<NewCompany> companyList;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public NewAddressBook() {}

  /**
   * All-args constructor.
   * @param personList The new value for personList
   * @param companyList The new value for companyList
   */
  public NewAddressBook(java.util.List<NewPerson> personList, java.util.List<NewCompany> companyList) {
    this.personList = personList;
    this.companyList = companyList;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public Object get(int field$) {
    switch (field$) {
    case 0: return personList;
    case 1: return companyList;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: personList = (java.util.List<NewPerson>)value$; break;
    case 1: companyList = (java.util.List<NewCompany>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'personList' field.
   * @return The value of the 'personList' field.
   */
  public java.util.List<NewPerson> getPersonList() {
    return personList;
  }

  /**
   * Sets the value of the 'personList' field.
   * @param value the value to set.
   */
  public void setPersonList(java.util.List<NewPerson> value) {
    this.personList = value;
  }

  /**
   * Gets the value of the 'companyList' field.
   * @return The value of the 'companyList' field.
   */
  public java.util.List<NewCompany> getCompanyList() {
    return companyList;
  }

  /**
   * Sets the value of the 'companyList' field.
   * @param value the value to set.
   */
  public void setCompanyList(java.util.List<NewCompany> value) {
    this.companyList = value;
  }

  /**
   * Creates a new NewAddressBook RecordBuilder.
   * @return A new NewAddressBook RecordBuilder
   */
  public static Builder newBuilder() {
    return new Builder();
  }

  /**
   * Creates a new NewAddressBook RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new NewAddressBook RecordBuilder
   */
  public static Builder newBuilder(Builder other) {
    return new Builder(other);
  }

  /**
   * Creates a new NewAddressBook RecordBuilder by copying an existing NewAddressBook instance.
   * @param other The existing instance to copy.
   * @return A new NewAddressBook RecordBuilder
   */
  public static Builder newBuilder(NewAddressBook other) {
    return new Builder(other);
  }

  /**
   * RecordBuilder for NewAddressBook instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<NewAddressBook>
    implements org.apache.avro.data.RecordBuilder<NewAddressBook> {

    private java.util.List<NewPerson> personList;
    private java.util.List<NewCompany> companyList;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.personList)) {
        this.personList = data().deepCopy(fields()[0].schema(), other.personList);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.companyList)) {
        this.companyList = data().deepCopy(fields()[1].schema(), other.companyList);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing NewAddressBook instance
     * @param other The existing instance to copy.
     */
    private Builder(NewAddressBook other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.personList)) {
        this.personList = data().deepCopy(fields()[0].schema(), other.personList);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.companyList)) {
        this.companyList = data().deepCopy(fields()[1].schema(), other.companyList);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'personList' field.
      * @return The value.
      */
    public java.util.List<NewPerson> getPersonList() {
      return personList;
    }

    /**
      * Sets the value of the 'personList' field.
      * @param value The value of 'personList'.
      * @return This builder.
      */
    public Builder setPersonList(java.util.List<NewPerson> value) {
      validate(fields()[0], value);
      this.personList = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'personList' field has been set.
      * @return True if the 'personList' field has been set, false otherwise.
      */
    public boolean hasPersonList() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'personList' field.
      * @return This builder.
      */
    public Builder clearPersonList() {
      personList = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'companyList' field.
      * @return The value.
      */
    public java.util.List<NewCompany> getCompanyList() {
      return companyList;
    }

    /**
      * Sets the value of the 'companyList' field.
      * @param value The value of 'companyList'.
      * @return This builder.
      */
    public Builder setCompanyList(java.util.List<NewCompany> value) {
      validate(fields()[1], value);
      this.companyList = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'companyList' field has been set.
      * @return True if the 'companyList' field has been set, false otherwise.
      */
    public boolean hasCompanyList() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'companyList' field.
      * @return This builder.
      */
    public Builder clearCompanyList() {
      companyList = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @SuppressWarnings("unchecked")
    public NewAddressBook build() {
      try {
        NewAddressBook record = new NewAddressBook();
        record.personList = fieldSetFlags()[0] ? this.personList : (java.util.List<NewPerson>) defaultValue(fields()[0]);
        record.companyList = fieldSetFlags()[1] ? this.companyList : (java.util.List<NewCompany>) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<NewAddressBook>
    WRITER$ = (org.apache.avro.io.DatumWriter<NewAddressBook>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<NewAddressBook>
    READER$ = (org.apache.avro.io.DatumReader<NewAddressBook>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
