/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.study.updateol.avro.oldprotocol;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class OldAddressBook extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8679724342030438714L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"OldAddressBook\",\"namespace\":\"com.study.updateol.avro.oldprotocol\",\"fields\":[{\"name\":\"personList\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"OldPerson\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"id\",\"type\":\"int\"},{\"name\":\"email\",\"type\":\"string\"}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<OldAddressBook> ENCODER =
      new BinaryMessageEncoder<OldAddressBook>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<OldAddressBook> DECODER =
      new BinaryMessageDecoder<OldAddressBook>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<OldAddressBook> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<OldAddressBook> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<OldAddressBook>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this OldAddressBook to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a OldAddressBook from a ByteBuffer. */
  public static OldAddressBook fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.util.List<com.study.updateol.avro.oldprotocol.OldPerson> personList;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public OldAddressBook() {}

  /**
   * All-args constructor.
   * @param personList The new value for personList
   */
  public OldAddressBook(java.util.List<com.study.updateol.avro.oldprotocol.OldPerson> personList) {
    this.personList = personList;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public Object get(int field$) {
    switch (field$) {
    case 0: return personList;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: personList = (java.util.List<com.study.updateol.avro.oldprotocol.OldPerson>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'personList' field.
   * @return The value of the 'personList' field.
   */
  public java.util.List<com.study.updateol.avro.oldprotocol.OldPerson> getPersonList() {
    return personList;
  }

  /**
   * Sets the value of the 'personList' field.
   * @param value the value to set.
   */
  public void setPersonList(java.util.List<com.study.updateol.avro.oldprotocol.OldPerson> value) {
    this.personList = value;
  }

  /**
   * Creates a new OldAddressBook RecordBuilder.
   * @return A new OldAddressBook RecordBuilder
   */
  public static Builder newBuilder() {
    return new Builder();
  }

  /**
   * Creates a new OldAddressBook RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new OldAddressBook RecordBuilder
   */
  public static Builder newBuilder(Builder other) {
    return new Builder(other);
  }

  /**
   * Creates a new OldAddressBook RecordBuilder by copying an existing OldAddressBook instance.
   * @param other The existing instance to copy.
   * @return A new OldAddressBook RecordBuilder
   */
  public static Builder newBuilder(OldAddressBook other) {
    return new Builder(other);
  }

  /**
   * RecordBuilder for OldAddressBook instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<OldAddressBook>
    implements org.apache.avro.data.RecordBuilder<OldAddressBook> {

    private java.util.List<com.study.updateol.avro.oldprotocol.OldPerson> personList;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.personList)) {
        this.personList = data().deepCopy(fields()[0].schema(), other.personList);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing OldAddressBook instance
     * @param other The existing instance to copy.
     */
    private Builder(OldAddressBook other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.personList)) {
        this.personList = data().deepCopy(fields()[0].schema(), other.personList);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'personList' field.
      * @return The value.
      */
    public java.util.List<com.study.updateol.avro.oldprotocol.OldPerson> getPersonList() {
      return personList;
    }

    /**
      * Sets the value of the 'personList' field.
      * @param value The value of 'personList'.
      * @return This builder.
      */
    public Builder setPersonList(java.util.List<com.study.updateol.avro.oldprotocol.OldPerson> value) {
      validate(fields()[0], value);
      this.personList = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'personList' field has been set.
      * @return True if the 'personList' field has been set, false otherwise.
      */
    public boolean hasPersonList() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'personList' field.
      * @return This builder.
      */
    public Builder clearPersonList() {
      personList = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @SuppressWarnings("unchecked")
    public OldAddressBook build() {
      try {
        OldAddressBook record = new OldAddressBook();
        record.personList = fieldSetFlags()[0] ? this.personList : (java.util.List<com.study.updateol.avro.oldprotocol.OldPerson>) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<OldAddressBook>
    WRITER$ = (org.apache.avro.io.DatumWriter<OldAddressBook>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<OldAddressBook>
    READER$ = (org.apache.avro.io.DatumReader<OldAddressBook>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
