/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.study.updateol.avro.oldprotocol;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface OldAvroService {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"OldAvroService\",\"namespace\":\"com.study.updateol.avro.oldprotocol\",\"types\":[{\"type\":\"record\",\"name\":\"OldPerson\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"id\",\"type\":\"int\"},{\"name\":\"email\",\"type\":\"string\"}]},{\"type\":\"record\",\"name\":\"OldAddressBook\",\"fields\":[{\"name\":\"personList\",\"type\":{\"type\":\"array\",\"items\":\"OldPerson\"}}]}],\"messages\":{\"send\":{\"request\":[{\"name\":\"addressBook\",\"type\":\"OldAddressBook\"}],\"response\":\"string\"}}}");
  /**
   */
  CharSequence send(OldAddressBook addressBook) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends OldAvroService {
    public static final org.apache.avro.Protocol PROTOCOL = OldAvroService.PROTOCOL;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void send(OldAddressBook addressBook, org.apache.avro.ipc.Callback<CharSequence> callback) throws java.io.IOException;
  }
}